services:
  db:
    image: postgres:17
    container_name: mi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nicololo
      POSTGRES_DB: mysafehaven
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
