services:
  db:
    image: postgres:17
    container_name: mysafehaven-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nicololo
      POSTGRES_DB: mysafehaven
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend/
    container_name: mysafehaven-backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contrase√±a
      POSTGRES_DB: midb
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  postgres_data:
